config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get '/:id' => 'home#show'

  devise_for :admins

  namespace :admin do
    resources :restaurants
  end

  # root to: "restaurants#index"

  root to: "home#index"
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	serialize :properties, JSON
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to admin_restaurant_path(id: @restaurant.id), notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to admin_restaurant_path(id: @restaurant.id), notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to admin_restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:title, :address, :description, :properties).tap do |whitelisted|
        whitelisted[:properties] = params[:restaurant][:properties]
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  after_action :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  protected

  def verified_request?
    super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  respond_to :json
  def index
    respond_to do |format|
      format.json { render json: Restaurant.all }
      format.html
    end
  end

  def show
 	  respond_to do |format|
      format.json { render json: Restaurant.find(params[:id]) }
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
<%= form_for [:admin, @restaurant], :html => { :class => "form-horizontal restaurant" } do |f| %>

  <% if @restaurant.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <%=f.error_span(:address) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <% if f.object.persisted? %>
    <div class="form-group">
      <%= f.label :properties, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :properties, :class => 'form-control' %>
      </div>
      <%=f.error_span(:address) %>
    </div>
  <% end %>

    <span class="addFields"></span><br>
  <hr><fieldset id="buildyourform">Add New Attributes
  </fieldset>
  <hr>
  <input type="button" value="Preview form" class="add" id="preview" />
  <input type="button" value="Add a field" class="add" id="add" />
  <br><br><br><br><br><br><br>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_restaurants_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

<script>
  $(document).ready(function() {
    $("#add").click(function() {
        var intId = $("#buildyourform div").length + 1;
        var fieldWrapper = $("<div class=\"fieldwrapper\" id=\"field" + intId + "\"/>");
        var fName = $("<input type=\"text\" class=\"fieldname\" />");
        var fType = $("<select class=\"fieldtype\"><option value=\"checkbox\">Checked</option><option value=\"textbox\">Text</option><option value=\"textarea\">Paragraph</option></select>");
        var removeButton = $("<input type=\"button\" class=\"remove\" value=\"-\" /><br><br>");
        removeButton.click(function() {
            $(this).parent().remove();
        });
        fieldWrapper.append(fName);
        fieldWrapper.append(fType);
        fieldWrapper.append(removeButton);
        $("#buildyourform").append(fieldWrapper);
    });


    $("#preview").click(function() {
        $("#yourform").remove();
        var fieldSet = $("<fieldset id=\"yourform\"><legend></legend></fieldset>");
        $("#buildyourform div").each(function() {
            var id = $(this).find("input.fieldname").first().val();
            var name = "restaurant[properties][" + $(this).find("input.fieldname").first().val();
            var label = $("<div class=\"form-group\"><label class=\"control-label col-lg-2\" for=\"" + id + "\">" + $(this).find("input.fieldname").first().val() + "</label>");
            var input;
            switch ($(this).find("select.fieldtype").first().val()) {
                case "checkbox":
                    input = $("<input type=\"checkbox\" id=\"" + id + "_id\" name=\"" + name + "]\" /><br>");
                    break;
                case "textbox":
                    input = $("<div class=\"col-lg-10\"><input type=\"text\" id=\"" + id + "_id\" name=\"" + name + "]\" class=\"form-control\"></div</div>");
                    break;
                case "textarea":
                    input = $("<div class=\"col-lg-10\"><textarea id=\"" + id + "_id\" name=\"" + name + "]\" class=\"form-control\"></textarea></div</div>");
                    break;
            }
            fieldSet.append(label);
            fieldSet.append(input);
        });
        $(".addFields").append(fieldSet);
    });
});

</script>

app/views/admin/restaurants/edit.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/restaurants/index.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:properties) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.id, admin_restaurant_path(restaurant) %></td>
        <td><%= restaurant.title %></td>
        <td><%= restaurant.address %></td>
        <td>
        <% restaurant.properties.each do |key, value| %>
          <p><%= key %> : <%= value %></p>
        <% end %></td>
        <td><%= link_to "Show", admin_restaurant_path(restaurant), :class => 'btn btn-warning btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_restaurant_path,
            :class => 'btn btn-primary' %>

app/views/admin/restaurants/new.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/restaurants/show.html.erb
<%- model_class = Restaurant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @restaurant.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @restaurant.address %></dd>
  <% @restaurant.properties.each do |key, value| %>
    <dt><strong><%= model_class.human_attribute_name(:"#{key}".to_sym) %>:</strong></dt>
    <dd><%= value %></dd>
  <% end %>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              admin_restaurants_path, :class => 'btn btn-default'  %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_restaurant_path(@restaurant),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/home/index.html.erb
<div ng-app="HomeCenter">

	<div ng-controller="homeCtrl">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Restaurant
                        <small>Near You</small>
                    </h1>
                </div>
            </div>
		    <div ng-repeat="restaurant in restaurants">
                 <div class="row">
                    <div class="col-md-4 portfolio-item">
                        <a href="/{{restaurant.id}}">
                            <img class="img-responsive" src="https://b.zmtcdn.com/data/pictures/2/20472/14a37a74923d15751ed71b7671e7c9b1_top_thumb_620_314.jpg?output-format=webp" alt="">
                        </a>
                   </div>
                        <h3>
                            <a href="/{{restaurant.id}}">{{restaurant.title}}</a>
                        </h3>
                        <p>{{restaurant.address}}</p>
                        <p ng-repeat="(key, val) in restaurant.properties">{{key}}: {{val}}</p> <br>
                </div><hr>
            </div>
		</div>
	</div>
</div>

<style>
    body {
        background-image:url('http://d1a9cyuca1q7uc.cloudfront.net/hq_images/c/celeste.jpg');
          background-size:cover;
          height:300px;
          opacity: .90;
    }
</style>

app/views/home/show.html.erb
<!-- Page Content -->
<div ng-app="Show">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <p class="lead">Categories</p>
        <div class="list-group">
          <a href="#" class="list-group-item active">Category 1</a>
          <a href="#" class="list-group-item">Category 2</a>
          <a href="#" class="list-group-item">Category 3</a>
        </div>
      </div>
      <div class="col-md-9">
        <div ng-controller="showCtrl">
          <div class="thumbnail">
            <img class="img-responsive" src="https://b.zmtcdn.com/data/res_imagery/18173090_RESTAURANT_bee20c25c8b2a562f6da60a139c5f7bd.jpg?output-format=webp" alt="">
            <div class="caption-full">
              <h4 class="pull-right">$24.99</h4>
              <h4><a href="#">{{restaurant.title}}</a>
              </h4>
              <p>{{restaurant.address}}</p>
              <p>Want to make these reviews work? Check out</p>
              <p>{{restaurant.description}}</p>
            </div>
            <div class="ratings">
              <p class="pull-right">3 reviews</p>
              <p>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star-empty"></span>
                4.0 stars
              </p>
            </div>
            <div class="well well-large">
              <ul class="menu">
                <p style="color:green;" ng-repeat="(key, val) in restaurant.properties">{{key}}: {{val}}</p>
              </ul>
            </div>
          </div>
          <div class="well">
            <div class="text-right">
              <a class="btn btn-success">Leave a Review</a>
            </div>
            <hr>
            <div class="row">
              <div class="col-md-12">
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star-empty"></span>
                Anonymous
                <span class="pull-right">10 days ago</span>
                <p>This product was great in terms of quality. I would definitely buy another!</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-md-12">
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star-empty"></span>
                Anonymous
                <span class="pull-right">12 days ago</span>
                <p>I've alredy ordered another one!</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-md-12">
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star-empty"></span>
                Anonymous
                <span class="pull-right">15 days ago</span>
                <p>I've seen some better than this, but not at this price. I definitely recommend this item.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /.container -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Restauranteur" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Restauranteur</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Admin", "/admin/restaurants"  %></li>
            <li><%= link_to "Link1", "#"  %></li>
            <li><%= link_to "Link2", "#"  %></li>
            <p class="navbar-text pull-right">
              <% if admin_signed_in? %>
                Logged in as <strong><%= current_admin.email %></strong>.
                <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
                <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
                <%= link_to "Sign up", new_admin_registration_path, :class => 'navbar-link'  %> |
                <%= link_to "Login", new_admin_session_path, :class => 'navbar-link'  %>
              <% end %>
              </p>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>